angular.module('cCatalogos', [])
    .factory('cEquipos', function () {
        return {
            tiposEquipos: [
                {id: 100, name: "Todos"},
                {id: 1, name: "Hidrolavadoras",
                    filtros: [
                        {id: 1, idTipo: 1, name: "Motor a gasolina"},
                        {id: 1, idTipo: 2, name: "Motor eléctrico"},
                        {id: 1, idTipo: 3, name: "Motor a diesel"},
                        {id: 1, idTipo: 4, name: "Comercial"},
                        {id: 1, idTipo: 5, name: "Industrial"},
                        {id: 1, idTipo: 6, name: "Agua fria"},
                        {id: 1, idTipo: 7, name: "Agua caliente"},
                        {id: 1, idTipo: 8, name: "Agua caliente/fria"},
                        // {id: 1, idTipo: 9, name: "Accsesorios"}
                    ]
                },
                {id: 2, name: "Motobombas",
                    filtros: [
                        {id: 2, idTipo: 1, name: "Motor a gasolina"},
                        {id: 2, idTipo: 1, name: "Motor a diesel"},
                        {id: 2, idTipo: 1, name: "Comercial"},
                        {id: 2, idTipo: 1, name: "Industrial"},
                        {id: 2, idTipo: 1, name: "Accsesorios"}
                    ]
                },
                {id: 3, name: "Aspiradoras",
                    filtros: [
                        {idTipo: 3, name: "Comercial"},
                        {idTipo: 2, name: "Industrial"},
                    ]
                },
                {id: 4, name: "Espumadores",
                    filtros: [
                        {id: 4, idTipo:1, name: "Comercial"},
                        {id: 4, idTipo:2, name: "Industrial"},
                    ]
                },
                {id: 5, name: "Generadores",
                    filtros: [
                        {id: 5, idTipo:1, name: "Comercial"},
                        {id: 5, idTipo:2, name: "Industrial"},
                    ]
                },
                {id: 6, name: "Torres de Iluminación", filtros: []},
                {id: 7, name: "Podadoras", filtros: []},
                {id: 8, name: "Desbrosadoras", filtros: []},
            ],

            hidrolavadoras: [
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua fría",
                    descripcion: "Hidrolavadora es para uso industrial con bomba de cigüeñal y bielas, para limpieza en industrias, de automóviles, camiones, piezas metálicas, pisos, etc., donde se requiera lavado a alta presión con agua fría.",
                    idSerie: 5,
                    descSerie: "Industrial",
                    idMotor: 2,
                    descMotor: "Electrica",
                    idTipoAgua: 6,
                    descTipoAgua: "Agua Fría",
                    marca: "POWERJET",
                    modelo: "F-150 Basic",
                    presion: "150 bares, (2,200 psig)",
                    potencia_de_motor: "5.5 hp, 1750 rpm",
                    peso: "48 Kg",
                    voltaje: "220 V",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: "",
                    caldera: null,
                    img: "hidrolavadoras/f-150.jpg"
                },
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua fría",
                    descripcion: "Esta hidrolavadora es para uso industrial, teniendo mucha potencia, para limpieza en industria química, metalúrgica etc., maquinaria pesada, piezas metálicas, pisos, etc., donde se requiera lavado con mucha presión con agua fría.",
                    idSerie: 5,
                    descSerie: "Industrial",
                    idMotor: 2,
                    descMotor: "Electrica",
                    idTipoAgua: 6,
                    descTipoAgua: "Agua Fría",
                    marca: "POWERJET",
                    modelo: "F-250",
                    presion: "250 bares, (3,625 psig)",
                    potencia_de_motor: "10 hp, 7.5 kw",
                    peso: "115 Kg",
                    voltaje: "220 o 440 V",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: "",
                    caldera: null,
                    img: "hidrolavadoras/f-250.jpg"
                },
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua fría",
                    descripcion: "Esta hidrolavadora es para uso industrial con bomba de cigüeñal y bielas, para limpieza en industrias, de automóviles, camiones, piezas metálicas, pisos, etc., con paro total y cubierta.",
                    idSerie: 5,
                    descSerie: "Industrial",
                    idMotor: 2,
                    descMotor: "Electrica",
                    idTipoAgua: 6,
                    descTipoAgua: "Agua Fría",
                    marca: "POWERJET",
                    modelo: "F-200",
                    presion: "200 bares, (3,000 psig)",
                    potencia_de_motor: "7.5 hp, 1750 rpm",
                    peso: "57 Kg",
                    voltaje: "220 o 440 V",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: "",
                    caldera: null,
                    img: "hidrolavadoras/f-200.jpg"
                },
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua caliente y fría",
                    descripcion: "Esta hidrolavadora es para uso industrial con bomba de cigüeñal y bielas, para limpieza en industrias, de automóviles, camiones, piezas metálicas, pisos, etc., con paro total y cubierta.",
                    idSerie: 5,
                    descSerie: "Industrial",
                    idMotor: 2,
                    descMotor: "Electrica",
                    idTipoAgua: 8,
                    descTipoAgua: "Agua Caliente y Fría",
                    marca: "POWERJET",
                    modelo: "TK-200/19 (Paro total retardado)",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "10 hp, 1750 rpm",
                    peso: "180 Kg",
                    voltaje: "220 o 440 V",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: "Diesel 5 kg/hr, 25 litros",
                    caldera: null,
                    img: "hidrolavadoras/tk-200-19.jpg"

                },
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua caliente y fría",
                    descripcion: "Esta hidrolavadora es propia para trabajo de uso rudo, con ayuda del agua caliente es óptima para remover grasa, aceite o mugre muy pegada de maquinaria, camiones, pisos, etc., en donde no cuenten con suministro eléctrico. También se puede producir vapor saturado, para aquellos lugares donde la presión puede dañar la superficie lavada.",
                    idSerie: 5,
                    descSerie: "Industrial",
                    idMotor: 1,
                    descMotor: "Gasolina",
                    idTipoAgua: 8,
                    descTipoAgua: "Agua Caliente y Fría",
                    marca: "POWERJET",
                    modelo: "C-200 G",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "18 hp, 1740 rpm",
                    peso: "170 Kg",
                    voltaje: "",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: " Diesel 5 kg/hr, 25 litros",
                    caldera: "A diesel, de doble serpentín",
                    img: "hidrolavadoras/c-200.jpg"
                },
                {
                    id: 1,
                    name: "Hidrolavadora industrial de alta presión en agua caliente y fría",
                    descripcion: "Esta hidrolavadora es propia para trabajo de uso rudo, con ayuda del agua caliente es óptima para remover grasa, aceite o mugre muy pegada de maquinaria, camiones, pisos, etc., en donde no cuenten con suministro eléctrico. También se puede producir vapor saturado, para aquellos lugares donde la presión puede dañar la superficie lavada.",
                    idSerie: 4,
                    descSerie: "Comercial",
                    idMotor: 1,
                    descMotor: "Gasolina",
                    idTipoAgua: 8,
                    descTipoAgua: "Agua Caliente y Fría",
                    marca: "POWERJET",
                    modelo: "C-200 G",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "18 hp, 1740 rpm",
                    peso: "170 Kg",
                    voltaje: "",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: " Diesel 5 kg/hr, 25 litros",
                    caldera: "A diesel, de doble serpentín",
                    img: "hidrolavadoras/c-200.jpg"
                }
            ],
            motobombas: [
                {
                    id: 2,
                    name: "Motobombas WMP20X",
                    descripcion: "Motobomba para agua salada y líquidos especiales utilizados en agricultura e industria, gracias a su carcasa de termoplástico reforzado.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: null,
                    descMotor: null,
                    idTipoAgua: null,
                    descTipoAgua: null,
                    marca: "HONDA",
                    modelo: "19006001",
                    presion: null,
                    potencia_de_motor: null,
                    peso: null,
                    voltaje: null,
                    conexion: null,
                    uso: "Industrial",
                    consumo: null,
                    caldera: null,
                    img: "motobombas/wmp-20-x.jpg"
                },
                {
                    id: 2,
                    name: "Motobomba WB20-XM",
                    descripcion: "Esta hidrolavadora es propia para trabajo de uso rudo, con ayuda del agua caliente es óptima para remover grasa, aceite o mugre muy pegada de maquinaria, camiones, pisos, etc., en donde no cuenten con suministro eléctrico. También se puede producir vapor saturado, para aquellos lugares donde la presión puede dañar la superficie lavada.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: null,
                    descMotor: null,
                    idTipoAgua: null,
                    descTipoAgua: null,
                    marca: "HONDA",
                    modelo: "GX 160H1",
                    presion: null,
                    potencia_de_motor: null,
                    peso: null,
                    voltaje: null,
                    conexion: null,
                    uso: "Industrial",
                    consumo: null,
                    caldera: null,
                    img: "motobombas/MB20X.jpg"
                }
            ],
            aspiradoras: [
                {
                    id: 3,
                    name: "Aspiradora Industrial",
                    descripcion: "Esta hidrolavadora es para uso industrial con bomba de cigüeñal y bielas, para limpieza en industrias, de automóviles, camiones, piezas metálicas, pisos, etc., con paro total y cubierta.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: 1,
                    descMotor: "2 de 1,200 watts c/u, 120 ó 220 V.",
                    idTipoAgua: null,
                    descTipoAgua: null,
                    marca: "POWERJET",
                    modelo: "Base 429 con expulsión",
                    presion: null,
                    potencia_de_motor: "3.2 hp (26 hp peak)",
                    peso: "22Kg",
                    voltaje: "120 ó 220 V",
                    conexion: null,
                    uso: "Industrial",
                    consumo: "2 de 1,200 watts c/u, 120 ó 220 V.",
                    caldera: null,
                    img: "aspiradoras/base-429.jpg"

                }
            ],
            espumadores: [
                {
                    id: 4,
                    name: "Espumador Industrial",
                    descripcion: "Esta hidrolavadora es propia para trabajo de uso rudo, con ayuda del agua caliente es óptima para remover grasa, aceite o mugre muy pegada de maquinaria, camiones, pisos, etc., en donde no cuenten con suministro eléctrico. También se puede producir vapor saturado, para aquellos lugares donde la presión puede dañar la superficie lavada.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: null,
                    descMotor: null,
                    idTipoAgua: 3,
                    descTipoAgua: "Agua Caliente y Fría",
                    marca: "POWERJET",
                    modelo: "C-200 G",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "18 hp, 1740 rpm",
                    peso: "170 Kg",
                    voltaje: "",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: " Diesel 5 kg/hr, 25 litros",
                    caldera: "A diesel, de doble serpentín",
                    img: "espumadores/espumador-inoxidable-50-litros.jpg"
                }
            ],
            generadores: [
                {
                    id: 5,
                    name: "Generador",
                    descripcion: "Esta hidrolavadora es para uso industrial con bomba de cigüeñal y bielas, para limpieza en industrias, de automóviles, camiones, piezas metálicas, pisos, etc., con paro total y cubierta.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: 2,
                    descMotor: "Gasolina",
                    idTipoAgua: 3,
                    descTipoAgua: "Agua Caliente y Fría",
                    marca: "POWERJET",
                    modelo: "TK-200/19 (Paro total retardado)",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "10 hp, 1750 rpm",
                    peso: "180 Kg",
                    voltaje: "220 o 440 V",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: "Diesel 5 kg/hr, 25 litros",
                    caldera: null,
                    img: "generadores/CALT4500B.jpg"

                },
                {
                    id: 5,
                    name: "Generador Industrial",
                    descripcion: "Esta hidrolavadora es propia para trabajo de uso rudo, con ayuda del agua caliente es óptima para remover grasa, aceite o mugre muy pegada de maquinaria, camiones, pisos, etc., en donde no cuenten con suministro eléctrico. También se puede producir vapor saturado, para aquellos lugares donde la presión puede dañar la superficie lavada.",
                    idSerie: 1,
                    descSerie: "Industrial",
                    idMotor: null,
                    descMotor: null,
                    idTipoAgua: 3,
                    descTipoAgua: null,
                    marca: "POWERJET",
                    modelo: "C-200 G",
                    presion: "200 Bares, (2,900 psig)",
                    potencia_de_motor: "18 hp, 1740 rpm",
                    peso: "170 Kg",
                    voltaje: "",
                    conexion: "Trifásica",
                    uso: "Industrial",
                    consumo: " Diesel 5 kg/hr, 25 litros",
                    caldera: "A diesel, de doble serpentín",
                    img: "generadores/generador.jpg"
                }
            ],
            torresIluminacion:[],
            podadoras: [],
            desbrosadoras:[],
            compresores:[]
        }
    });